sudo: false
language: "python"
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
addons:
  apt:
    packages:
      - git
      - python-pip
install:
  - pip install -r requirements.txt
script:
  - python setup.py test
after_success:
- if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
